name: Increment Version
on:
  workflow_call:
    inputs:
      increment:
        required: true
        type: string
      dry-run:
        required: true
        type: boolean
      channel:
        required: true
        type: string
      git-repo:
        required: true
        type: string
      latest-release:
        required: true
        type: string
      next-version:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
    outputs:
      version:
        description: 'The new package.json version, e.g. "0.16.0"'
        value: ${{ inputs.next-version }}
      tag-ref:
        description: 'The fully qualified ref for the tag, e.g. "refs/tags/v0.16.0"'
        value: ${{ jobs.release.outputs.tag-ref }}
      latest-release:
        description: 'The latest release (per GitHub releases) prior to this increment, e.g. "v0.15.0"'
        value: ${{ inputs.latest-release }}
      changelog:
        description: "The changelog from latest-release to version if it is the latest release channel"
        value: ${{ jobs.release.outputs.changelog }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag-ref: ${{ steps.increment-version.outputs.tag-ref }}
      changelog: ${{ steps.increment-version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: |
          git config user.name "Lexical Builder GitHub Actions Bot"
          git config user.email "<>"
      - id: increment-version
        run: npm run increment-version
        env:
          # These are passed in the environment as they are used by
          # the postversion script
          INCREMENT: ${{ inputs.increment }}
          CHANNEL: ${{ inputs.channel }}
          NEXT_VERSION: ${{ inputs.next-version }}
          LATEST_RELEASE: ${{ inputs.latest-release }}
          DRY_RUN: ${{ inputs.dry-run && '1' || '' }}
          GIT_REPO: ${{ inputs.git-repo }}
