name: Nightly Release Branch
on:
  # Run daily at 2:30am UTC
  schedule:
    - cron: "30 2 * * 1-5"
  workflow_dispatch:
jobs:
  get-settings:
    runs-on: ubuntu-latest
    outputs:
      increment: prerelease
      channel: nightly
    steps:
      - run: exit 0
  get-versions:
    needs: [get-settings]
    uses: ./.github/workflows/call-get-versions.yml
    with:
      increment: ${{ needs.get-settings.outputs.increment }}
      channel: ${{ needs.get-settings.outputs.channel }}
  increment-version:
    # prevents this action from running on forks
    if: github.repository_owner == 'etrepum'
    needs: [get-settings, get-versions]
    uses: ./.github/workflows/call-increment-version.yml
    with:
      increment: ${{ needs.get-settings.outputs.increment }}
      channel: ${{ needs.get-settings.outputs.channel }}
      latest-release: ${{ needs.get-versions.outputs.latest-release }}
      next-version: ${{ needs.get-versions.outputs.next-version }}
      dry-run: false
      git-repo: ${{ needs.get-versions.outputs.ssh-git-origin }}
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
  npm-release:
    uses: ./.github/workflows/call-npm-publish.yml
    needs: [get-settings, increment-version]
    with:
      ref: ${{ needs.increment-version.outputs.tag-ref }}
      dry-run: false
      channel: ${{ needs.get-settings.outputs.channel }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
