name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      otp:
        description: '(optional) one-time password'
        type: string

jobs:
  release:
    uses: ./.github/workflows/call-npm-publish.yml
    with:
      ref: main
      dry-run: false
      channel: latest
      otp: ${{ inputs.otp }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
