name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'release channel'
        type: choice
        options:
          - latest
          - next
          - nightly
        default: latest

jobs:
  release:
    uses: ./.github/workflows/call-npm-publish.yml
    with:
      ref: refs/heads/${{ inputs.channel }}__release
      dry-run: false
      channel: ${{ inputs.channel }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
