name: Create New Release Branch
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version Increment'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prerelease
          - patch
          - minor
jobs:
  increment-version:
    uses: ./.github/workflows/call-increment-version.yml
    with:
      increment: ${{ inputs.increment }}
      dry-run: false
      channel: ${{ inputs.increment == 'prerelease' && 'next' || 'latest' }}
      git-repo: 'git@github.com:etrepum/lexical-builder.git'
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
  draft-latest-release:
    needs: [increment-version]
    runs-on: ubuntu-latest
    if: needs.increment-version.outputs.changelog && inputs.increment != 'prerelease'
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{ needs.increment-version.outputs.changelog }}
          tag_name: v${{ needs.increment-version.outputs.version }}
